# Generated by Django 2.1.2 on 2018-10-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('SubTasks', models.TextField()),
                ('Status', models.TextField()),
                ('DueDate', models.DateField()),
                ('Alert', models.IntegerField()),
                ('Symbol', models.TextField()),
                ('Visibility', models.TextField()),
                ('HardDeleteDate', models.DateField(null=True)),
                ('Local_id', models.CharField(max_length=60)),
            ],
        ),
    ]
